web:
  build: ./..
  dockerfile: Dockerfile
  ports:
    - "80:80"
  environment:
    - SECRET=2394utrjfdg920844258hgj9485hglkdmv
    - APP_SETTINGS=production

nginx:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf:ro


sut:
  build: .
  dockerfile: Dockerfile.test
  links:
    - web
    - nginx